name: Daily Job Scrape
permissions:
  contents: write

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Run daily scrape
        run: node scrape/scrape.js

      - name: List all CSVs
        run: |
          echo "Workspace at $(pwd)"
          find "$(pwd)" -type f -name '*.csv' -exec echo "  → {}" ';'

      - name: "Debug: show CSV head"
        run: |
          head -n 5 scrape/job_listings.csv || echo "(missing)"
          head -n 5 scrape/sponsored_jobs.csv || echo "(missing)"

      - name: Archive CSVs
        run: |
          TIMESTAMP=$(date -u +'%Y-%m-%d_%H%M')
          mkdir -p archive
          cp scrape/job_listings.csv  archive/job_listings_${TIMESTAMP}.csv
          cp scrape/sponsored_jobs.csv archive/sponsored_jobs_${TIMESTAMP}.csv || echo "no sponsored file"

      - name: Commit & push updated CSVs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          # stage
          git add scrape/job_listings.csv scrape/sponsored_jobs.csv archive/*.csv
          # show what’s currently staged
          echo "→ git diff --cached:"; git diff --cached --name-status
          # commit if there are changes
          git diff --cached --quiet \
            || git commit -m "chore: automated daily scrape & archive"
          # push and show the result
          git push --verbose
