name: Daily Job Scrape

on:
  schedule:
    - cron: '0 0 * * *'      # daily at midnight UTC
  workflow_dispatch:        # ← this line is essential for manual runs

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          persist-credentials: true

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run daily scrape
        run: node scrape/scrape.js

      - name: Archive CSVs
        run: |
          TIMESTAMP=$(date -u +'%Y-%m-%d_%H%M')
          mkdir -p archive
          cp scrape/job_listings.csv archive/job_listings_${TIMESTAMP}.csv
          cp scrape/sponsored_jobs.csv archive/sponsored_jobs_${TIMESTAMP}.csv

      - name: Commit updated + archived CSVs
        uses: EndBug/add-and-commit@v9
        with:
          add: |
            scrape/job_listings.csv,
            scrape/sponsored_jobs.csv,
            archive/**/*.csv
          message: chore: automated daily scrape & archive

