name: Daily Job Scrape
permissions:
  contents: write

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Run scraper
        run: node scrape/scrape.js

      - name: Inspect generated CSVs
        run: |
          echo "Files in repo:"
          ls -R .
          echo "— job_listings.csv —"
          head -n5 scrape/job_listings.csv
          echo "— sponsored_jobs.csv —"
          head -n5 scrape/sponsored_jobs.csv

      - name: Commit & push CSVs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add scrape/job_listings.csv scrape/sponsored_jobs.csv archive/*.csv
          echo "→ git diff --cached:"; git diff --cached --name-status
          git diff --cached --quiet \
            || git commit -m "chore: automated daily scrape & archive"
          git push --verbose
