name: Daily Scrape

on:
  schedule:
    - cron: '0 13 * * *' # Runs every day at 13:00 UTC (midnight Sydney time)
  workflow_dispatch: # Allows manual triggering of the workflow
  push:
    branches:
      - main

jobs:
  scrape:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '23' # Specify the Node.js version you need

    - name: Install dependencies
      run: npm install
      working-directory: ./scrape

    #- name: Create scrape directory
    #  run: mkdir -p ./scrape  

    - name: Download job_listings.csv
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
          $headers = @{
          Authorization = "token $env:GITHUB_TOKEN"
          Accept        = "application/vnd.github.v3.raw"
          }
          Invoke-RestMethod -Uri https://api.github.com/repos/paskie-fcj/find-care-jobs/contents/scrape/job_listings.csv -Headers $headers -OutFile "./scrape/job_listings.csv"

    - name: Run scrape script
      run: node scrape.js
      working-directory: ./scrape
